### ISSUE TITLE
vacstepvolume

### ISSUE THREAD

**Issue by JennPopp** [JennPopp/leap_sims_master#22]
Are photons counted multiple times in the vacstep?

**Comment by JennPopp** [comment]
I suggest to make the following change in the stepping action and compare that to the previous results

// get pre-step-volume of the current aStep
  auto prevolume = aStep->GetPreStepPoint()->GetTouchableHandle()->GetVolume();
//get post-step-volume of the current aStep
auto postvolume = aStep->GetPostStepPoint()->GetTouchableHandle()->GetVolume();
//get vacstep volume
auto VacStep2PV=fDetector->GetVacStep2PV()
  if (outputType == "bunch"){
    if ( postvolume == VacStep2PV && prevolume !=VacStep2PV  )
      {write stuff in ttree}

**Comment by FelixStehr** [comment]
The If-Statement works, thanks =)
