### ISSUE TITLE
add If-Statement to the VacStep and use PostStep 

### ISSUE THREAD

**Issue by FelixStehr** [JennPopp/leap_sims_master#24]
Uniform use of PostStep instead of PreStep and implementation of the If-Statement (see below) so that nothing is counted twice

**Comment by FelixStehr** [comment]
// get pre-step-volume of the current aStep
auto prevolume = aStep->GetPreStepPoint()->GetTouchableHandle()->GetVolume();
//get post-step-volume of the current aStep
auto postvolume = aStep->GetPostStepPoint()->GetTouchableHandle()->GetVolume();
//get vacstep volume
auto VacStep2PV=fDetector->GetVacStep2PV()
if (outputType == "bunch"){
if ( postvolume == VacStep2PV && prevolume !=VacStep2PV )
{write stuff in ttree}

**Comment by JennPopp** [comment]
But its still necessary to consider negative momentum in analysis!
